### ISSUE TITLE
creation of linking tool  

### ISSUE THREAD

**Issue by opheliagame** [an-online-reading-room/reading-room-platform#1]
The adventure mode allows moving between stories through links created by users. 
Links function like normal hyperlinks.

**Comment by opheliagame** [comment]
- should a story be able to link to themselves?
- storing links directly in doc vs separately 
- storing user info with links   
- selecting parts of the story that already have links?

https://stackoverflow.com/questions/31285213/highlight-text-in-html-by-int-offset-start-end-without-knowing-actual-textnode

**Comment by rndexe** [comment]
- check if block id changes when you edit story

**Comment by opheliagame** [comment]
having issues with slug field in story 
https://forum.strapi.io/t/uid-property-is-null-in-get-response-to-the-strapi-rest-api/16152
ref https://github.com/strapi/strapi/issues/11665

**Comment by rndexe** [comment]
Just leaving this here because I saw it yesterday, dunno if it's relavent enough
https://www.youtube.com/watch?v=OVV0CfgX6Qk

**Comment by opheliagame** [comment]
> Just leaving this here because I saw it yesterday, dunno if it's relavent enough https://www.youtube.com/watch?v=OVV0CfgX6Qk

interesting but transfers the responsibility of creating the slug during the create process. with the strapi slug system, we don't have to specifically create a slug, strapi does it for us but currently there is some bug over there so will maybe have to look for a solution in the meantime

**Comment by rndexe** [comment]
so slug is only automatically generated when creating a post from the admin panel. When creating a post through the api we can auto-generate as mentioned here. Basically we need to add  beforeCreate and beforeUpdate lifecycle function.
However there'd be an issue there when autosaving, as if the story doesn't have a title we'd have to generate a slug such as untitles-${id}

https://forum.strapi.io/t/generate-attached-field-uid-on-post-request/1645

Or using this plugin
https://market.strapi.io/plugins/strapi-plugin-slugify

Or this if we don't want to check for already existing slugs
https://docs.strapi.io/developer-docs/latest/guides/slug.html

**Comment by opheliagame** [comment]
@rndexe oh that is wonderful then, i did not consult these before. could you fix the slug system, i'll leave it to you which of the three ways you want to use, given the slug field is used as an ID for each story.

**Comment by opheliagame** [comment]
@rndexe i have pushed an update to strapi with lifecycle hooks for map and story 
ref #3

**Comment by rndexe** [comment]
Oh I had also just added it today. Will check.
