### ISSUE TITLE
minor release for testing 

### ISSUE THREAD

**Issue by opheliagame** [an-online-reading-room/reading-room-platform#2]
im not quite sure how to use github issues so just experimenting here.
opening this @kneetis @rndexe to keep track of issues that might pop up with the new build that i will push soon 🎉

**Comment by rndexe** [comment]
Tracking bugs with neeti here

https://spangled-purple-50d.notion.site/Errors-Issues-Bugs-e3b27e8d22d648b1b4c66588eeafc71e
