### ISSUE TITLE
fix - using an already existing email with another username 

### ISSUE THREAD

**Issue by opheliagame** [an-online-reading-room/reading-room-platform#6]
if i try to login or signup as a new user, with a new username, using an already existing email, i get logged in as the previous user.
instead of this, we should present some sort of error or warning message indicating that the email being entered is already in use with another username

**Comment by rndexe** [comment]
This is a limitation of the passwordless plugin, I'll see if it can be extended easily otherwise this might have to remain

**Comment by opheliagame** [comment]
@rndexe before sending it to passwordless can we not validate the email address?

**Comment by rndexe** [comment]
I don't think there's an api route for that, I'll check if there is.
