### ISSUE TITLE
fix - random endpoint also returns draft versions of stories  

### ISSUE THREAD

**Issue by opheliagame** [an-online-reading-room/reading-room-platform#8]

**Comment by rndexe** [comment]
Is this an endpoint you made yourself? Ideally /stories/:id endpoint shouldn't return draft versions. 
There is a publicationState you can query or you can also check for publishedAt attribute. If it is null, it is a draft version.

**Comment by opheliagame** [comment]
@rndexe yes it is a custom endpoint. i figured i should check the published_at column, but just in case what is publishedState and where is it

**Comment by opheliagame** [comment]
ref https://github.com/an-online-reading-room/reading-room-backend/issues/4

**Comment by rndexe** [comment]
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#filtering

It's at the end, you can add publication state to query

**Comment by opheliagame** [comment]
@rndexe link doesnt seem to be working..
